# GEOparse
https://geoparse.readthedocs.io/en/latest/GEOparse.html

In [1]:
import GEOparse
import pandas as pd

In [2]:
import pylab as pl
import seaborn as sns
pl.rcParams['figure.figsize'] = (14, 10)
pl.rcParams['ytick.labelsize'] = 12
pl.rcParams['xtick.labelsize'] = 11
pl.rcParams['axes.labelsize'] = 23
pl.rcParams['legend.fontsize'] = 20
sns.set_style('ticks')
c1, c2, c3, c4 = sns.color_palette("Set1", 4)

In [3]:
gse = GEOparse.get_GEO("GSE126848")

08-Sep-2020 14:11:22 DEBUG utils - Directory ./ already exists. Skipping.
08-Sep-2020 14:11:22 INFO GEOparse - Downloading ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE126nnn/GSE126848/soft/GSE126848_family.soft.gz to ./GSE126848_family.soft.gz
100%|██████████| 4.46k/4.46k [00:00<00:00, 4.57kB/s]
08-Sep-2020 14:11:28 DEBUG downloader - Size validation passed
08-Sep-2020 14:11:28 DEBUG downloader - Moving /tmp/tmp19kovpgb to /data/home/mickey24/signatureSearch/GSE126848_family.soft.gz
08-Sep-2020 14:11:28 DEBUG downloader - Successfully downloaded ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE126nnn/GSE126848/soft/GSE126848_family.soft.gz
08-Sep-2020 14:11:28 INFO GEOparse - Parsing ./GSE126848_family.soft.gz:
08-Sep-2020 14:11:28 DEBUG GEOparse - DATABASE: GeoMiame
08-Sep-2020 14:11:28 DEBUG GEOparse - SERIES: GSE126848
08-Sep-2020 14:11:28 DEBUG GEOparse - PLATFORM: GPL18573
08-Sep-2020 14:11:28 DEBUG GEOparse - SAMPLE: GSM3615293
08-Sep-2020 14:11:28 DEBUG GEOparse - SAMPLE: GSM3615294
08-Sep-2020 14:11:28 DEBUG GEOparse - SAMPLE: GSM3615295
08-Sep-2020 14:11:28 DEBUG GEOparse - SAMPLE: GSM3615296
08-Sep-2020 14:11:28 DEBUG GEOparse - SAMPLE: GSM3615297
08-Sep-2020 14:11:28 DEBUG GEOparse - SAMPLE: GSM3615298
08-Sep-2020 14:11:28 DEBUG GEOparse - SAMPLE: GSM3615299
08-Sep-2020 14:11:28 DEBUG GEOparse - SAMPLE: GSM3615300
08-Sep-2020 14:11:28 DEBUG GEOparse - SAMPLE: GSM3615301
08-Sep-2020 14:11:28 DEBUG GEOparse - SAMPLE: GSM3615302
08-Sep-2020 14:11:28 DEBUG GEOparse - SAMPLE: GSM3615303
08-Sep-2020 14:11:28 DEBUG GEOparse - SAMPLE: GSM3615304
08-Sep-2020 14:11:28 DEBUG GEOparse - SAMPLE: GSM3615305
08-Sep-2020 14:11:28 DEBUG GEOparse - SAMPLE: GSM3615306
08-Sep-2020 14:11:28 DEBUG GEOparse - SAMPLE: GSM3615307
08-Sep-2020 14:11:28 DEBUG GEOparse - SAMPLE: GSM3615308
08-Sep-2020 14:11:28 DEBUG GEOparse - SAMPLE: GSM3615309
08-Sep-2020 14:11:28 DEBUG GEOparse - SAMPLE: GSM3615310
08-Sep-2020 14:11:28 DEBUG GEOparse - SAMPLE: GSM3615311
08-Sep-2020 14:11:28 DEBUG GEOparse - SAMPLE: GSM3615312
08-Sep-2020 14:11:28 DEBUG GEOparse - SAMPLE: GSM3615313
08-Sep-2020 14:11:28 DEBUG GEOparse - SAMPLE: GSM3615314
08-Sep-2020 14:11:28 DEBUG GEOparse - SAMPLE: GSM3615315
08-Sep-2020 14:11:28 DEBUG GEOparse - SAMPLE: GSM3615316
08-Sep-2020 14:11:28 DEBUG GEOparse - SAMPLE: GSM3615317
08-Sep-2020 14:11:28 DEBUG GEOparse - SAMPLE: GSM3615318
08-Sep-2020 14:11:28 DEBUG GEOparse - SAMPLE: GSM3615319
08-Sep-2020 14:11:28 DEBUG GEOparse - SAMPLE: GSM3615320
08-Sep-2020 14:11:28 DEBUG GEOparse - SAMPLE: GSM3615321
08-Sep-2020 14:11:28 DEBUG GEOparse - SAMPLE: GSM3615322
08-Sep-2020 14:11:28 DEBUG GEOparse - SAMPLE: GSM3615323
08-Sep-2020 14:11:28 DEBUG GEOparse - SAMPLE: GSM3615324
08-Sep-2020 14:11:28 DEBUG GEOparse - SAMPLE: GSM3615325
08-Sep-2020 14:11:28 DEBUG GEOparse - SAMPLE: GSM3615326
08-Sep-2020 14:11:28 DEBUG GEOparse - SAMPLE: GSM3615327
08-Sep-2020 14:11:28 DEBUG GEOparse - SAMPLE: GSM3615328
08-Sep-2020 14:11:28 DEBUG GEOparse - SAMPLE: GSM3615329
08-Sep-2020 14:11:28 DEBUG GEOparse - SAMPLE: GSM3615330
08-Sep-2020 14:11:28 DEBUG GEOparse - SAMPLE: GSM3615331
08-Sep-2020 14:11:28 DEBUG GEOparse - SAMPLE: GSM3615332
08-Sep-2020 14:11:28 DEBUG GEOparse - SAMPLE: GSM3615333
08-Sep-2020 14:11:28 DEBUG GEOparse - SAMPLE: GSM3615334
08-Sep-2020 14:11:28 DEBUG GEOparse - SAMPLE: GSM3615335
08-Sep-2020 14:11:28 DEBUG GEOparse - SAMPLE: GSM3615336
08-Sep-2020 14:11:28 DEBUG GEOparse - SAMPLE: GSM3615337
08-Sep-2020 14:11:28 DEBUG GEOparse - SAMPLE: GSM3615338
08-Sep-2020 14:11:28 DEBUG GEOparse - SAMPLE: GSM3615339
08-Sep-2020 14:11:28 DEBUG GEOparse - SAMPLE: GSM3615340
08-Sep-2020 14:11:28 DEBUG GEOparse - SAMPLE: GSM3615341
08-Sep-2020 14:11:28 DEBUG GEOparse - SAMPLE: GSM3615342
08-Sep-2020 14:11:28 DEBUG GEOparse - SAMPLE: GSM3615343
08-Sep-2020 14:11:28 DEBUG GEOparse - SAMPLE: GSM3615344
08-Sep-2020 14:11:28 DEBUG GEOparse - SAMPLE: GSM3615345
08-Sep-2020 14:11:28 DEBUG GEOparse - SAMPLE: GSM3615346
08-Sep-2020 14:11:28 DEBUG GEOparse - SAMPLE: GSM3615347
08-Sep-2020 14:11:28 DEBUG GEOparse - SAMPLE: GSM3615348
08-Sep-2020 14:11:28 DEBUG GEOparse - SAMPLE: GSM3615349

In [5]:
gse.gsms['GSM3615293'].metadata

{'title': ['NAFL_1'],
 'geo_accession': ['GSM3615293'],
 'status': ['Public on Feb 22 2019'],
 'submission_date': ['Feb 21 2019'],
 'last_update_date': ['Feb 22 2019'],
 'type': ['SRA'],
 'channel_count': ['1'],
 'source_name_ch1': ['Liver needle biopsy'],
 'organism_ch1': ['Homo sapiens'],
 'taxid_ch1': ['9606'],
 'characteristics_ch1': ['gender: Male', 'tissue: Liver', 'disease: NAFLD'],
 'molecule_ch1': ['polyA RNA'],
 'extract_protocol_ch1': ['TruSeq® Stranded mRNA Library Prep for NeoPrep',
  'RNA was isolated from fine needle biopsies of human livers using NucleoSpin® from MACHEREY-NAGEL according to manufactors protocol'],
 'description': ['2683'],
 'data_processing': ['bcl2fastq v2.17.1.14 used for basecalling',
  'Sequenced reads were mapped to Ensembl Mus musculus genome using whole genome using STAR v2.5.2a with default parameters',
  'Filtering for protein coding genes',
  'Genome_build: Ensembl GRCh38 89',
  'Supplementary_files_format_and_content: Count table'],
 'platform_id': ['GPL18573'],
 'contact_name': ['Kristoffer,,Rigbolt'],
 'contact_email': ['kri@gubra.dk'],
 'contact_institute': ['Gubra'],
 'contact_address': ['Hørsholm Kongevej 11B'],
 'contact_city': ['Hørsholm'],
 'contact_zip/postal_code': ['2970'],
 'contact_country': ['Denmark'],
 'instrument_model': ['Illumina NextSeq 500'],
 'library_selection': ['cDNA'],
 'library_source': ['transcriptomic'],
 'library_strategy': ['RNA-Seq'],
 'relation': ['BioSample: https://www.ncbi.nlm.nih.gov/biosample/SAMN10979953',
  'SRA: https://www.ncbi.nlm.nih.gov/sra?term=SRX5401559'],
 'supplementary_file_1': ['NONE'],
 'series_id': ['GSE126848'],
 'data_row_count': ['0']}

In [7]:
gsm_id_dict=dict()
for gsm_id in gse.gsms:
    desc = gse.gsms[gsm_id].metadata['description']
    gsm_id_dict[desc[0].zfill(4)] = gsm_id
#    print(desc[0].zfill(4) ,gsm_id)

In [8]:
gse.metadata['supplementary_file']

['ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE126nnn/GSE126848/suppl/GSE126848_Gene_counts_raw.txt.gz']

In [9]:
df = pd.read_csv(gse.metadata['supplementary_file'][0], sep='\t', index_col=0)

In [10]:
df.head()

,0869,0872,0873,0874,0875,0876,0877,0878,0879,0881,...,3997,3998,4000,4002,4004,4005,4006,4007,4008,4010
key,,,,,,,,,,,,,,,,,,,,,
ENSG00000186092,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ENSG00000278566,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ENSG00000273547,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ENSG00000187634,28,32,13,11,37,30,16,19,6,12,...,36,17,43,23,44,73,5,40,25,6
ENSG00000188976,882,815,542,695,665,778,892,626,435,417,...,444,176,535,376,523,503,69,482,440,226

In [11]:
df.columns = df.columns.map(str).map(gsm_id_dict)

In [12]:
df.head()

,GSM3615324,GSM3615338,GSM3615325,GSM3615339,GSM3615326,GSM3615340,GSM3615327,GSM3615341,GSM3615328,GSM3615329,...,GSM3615318,GSM3615304,GSM3615319,GSM3615305,GSM3615320,GSM3615321,GSM3615322,GSM3615306,GSM3615323,GSM3615307
key,,,,,,,,,,,,,,,,,,,,,
ENSG00000186092,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ENSG00000278566,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ENSG00000273547,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ENSG00000187634,28,32,13,11,37,30,16,19,6,12,...,36,17,43,23,44,73,5,40,25,6
ENSG00000188976,882,815,542,695,665,778,892,626,435,417,...,444,176,535,376,523,503,69,482,440,226

In [13]:
import mygene
mg = mygene.MyGeneInfo()
mg_df = mg.getgenes(df.index, fields='entrezgene',as_dataframe=True)
df.insert(0,'entrezgene',mg_df.entrezgene)

import numpy as np
df.entrezgene = df.entrezgene.astype(str)
df_nodup=df[df.entrezgene!='nan']

querying 1-1000...done.
querying 1001-2000...done.
querying 2001-3000...done.
querying 3001-4000...done.
querying 4001-5000...done.
querying 5001-6000...done.
querying 6001-7000...done.
querying 7001-8000...done.
querying 8001-9000...done.
querying 9001-10000...done.
querying 10001-11000...done.
querying 11001-12000...done.
querying 12001-13000...done.
querying 13001-14000...done.
querying 14001-15000...done.
querying 15001-16000...done.
querying 16001-17000...done.
querying 17001-18000...done.
querying 18001-19000...done.
querying 19001-19786...done.

In [35]:
dup_entrez=df_nodup[df_nodup.entrezgene.duplicated()].entrezgene.tolist()
sub_df = df[df.entrezgene.isin(dup_entrez)]
sub_df = sub_df.reset_index()
sub_df

,key,entrezgene,GSM3615324,GSM3615338,GSM3615325,GSM3615339,GSM3615326,GSM3615340,GSM3615327,GSM3615341,...,GSM3615318,GSM3615304,GSM3615319,GSM3615305,GSM3615320,GSM3615321,GSM3615322,GSM3615306,GSM3615323,GSM3615307
0,ENSG00000283765,55486,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,ENSG00000175193,55486,129,103,70,92,109,141,166,101,...,124,56,189,119,141,140,37,87,136,65
2,ENSG00000280987,9782,0,0,1,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
3,ENSG00000015479,9782,44,1,6,6,7,0,27,6,...,8,4,23,6,33,8,17,11,10,0
4,ENSG00000158427,286527,0,0,0,0,0,0,0,1,...,0,0,0,0,0,2,2,0,1,0
5,ENSG00000269226,286527,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,ENSG00000260548,8471,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,ENSG00000133124,8471,0,0,0,0,0,0,2,0,...,0,0,0,0,0,0,0,0,0,0
8,ENSG00000258724,54984,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,ENSG00000254093,54984,62,65,45,39,38,43,58,31,...,24,10,28,45,40,51,7,51,21,12
10,ENSG00000187522,51182,116,87,50,49,77,55,120,61,...,26,10,56,34,62,48,18,62,57,18
11,ENSG00000284024,51182,12,10,2,6,14,6,12,4,...,0,0,4,3,3,3,1,0,5,0
12,ENSG00000261130,255027,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,ENSG00000156968,255027,572,368,351,287,410,412,579,266,...,109,33,351,146,463,158,41,159,193,111
14,ENSG00000268861,23370,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,ENSG00000104880,23370,126,148,66,80,60,78,100,72,...,11,11,15,16,32,27,0,23,10,16
16,ENSG00000196081,440519,6,2,3,3,0,0,2,0,...,0,0,0,0,5,1,0,5,0,0
17,ENSG00000283201,440519,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [15]:
# sub_df['SUM']=sub_df.iloc[:,1:].sum(axis=1)
# df_nodup = df_nodup.drop(sub_df[sub_df['SUM']==0].index)
# df_nodup.shape

/data/home/mickey24/miniconda3/envs/CGAN/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

(19178, 58)

In [38]:
sub_df.groupby(sub_df.entrezgene).min().key

entrezgene
23370     ENSG00000104880
255027    ENSG00000156968
286527    ENSG00000158427
440519    ENSG00000196081
51182     ENSG00000187522
54984     ENSG00000254093
55486     ENSG00000175193
8471      ENSG00000133124
9782      ENSG00000015479
Name: key, dtype: object

In [39]:
df_nodup2 = df[df.entrezgene!='nan']
df_nodup2 = df_nodup2[~df_nodup2.index.isin(sub_df.groupby(sub_df.entrezgene).min().key)]
df_nodup2.shape

(19175, 58)

In [41]:
df_nodup2[df_nodup2.entrezgene.duplicated()]

Empty DataFrame
Columns: [entrezgene, GSM3615324, GSM3615338, GSM3615325, GSM3615339, GSM3615326, GSM3615340, GSM3615327, GSM3615341, GSM3615328, GSM3615329, GSM3615330, GSM3615331, GSM3615342, GSM3615332, GSM3615343, GSM3615333, GSM3615344, GSM3615334, GSM3615345, GSM3615335, GSM3615346, GSM3615347, GSM3615336, GSM3615348, GSM3615349, GSM3615337, GSM3615293, GSM3615308, GSM3615294, GSM3615295, GSM3615309, GSM3615296, GSM3615297, GSM3615310, GSM3615298, GSM3615311, GSM3615299, GSM3615312, GSM3615300, GSM3615301, GSM3615313, GSM3615314, GSM3615315, GSM3615302, GSM3615316, GSM3615303, GSM3615317, GSM3615318, GSM3615304, GSM3615319, GSM3615305, GSM3615320, GSM3615321, GSM3615322, GSM3615306, GSM3615323, GSM3615307]
Index: []

[0 rows x 58 columns]

In [43]:
df_nodup2 = df_nodup2.set_index('entrezgene',drop=True)
df_nodup2.head()

,GSM3615324,GSM3615338,GSM3615325,GSM3615339,GSM3615326,GSM3615340,GSM3615327,GSM3615341,GSM3615328,GSM3615329,...,GSM3615318,GSM3615304,GSM3615319,GSM3615305,GSM3615320,GSM3615321,GSM3615322,GSM3615306,GSM3615323,GSM3615307
entrezgene,,,,,,,,,,,,,,,,,,,,,
79501,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
148398,28,32,13,11,37,30,16,19,6,12,...,36,17,43,23,44,73,5,40,25,6
26155,882,815,542,695,665,778,892,626,435,417,...,444,176,535,376,523,503,69,482,440,226
339451,30,15,19,16,7,22,27,19,9,11,...,0,7,14,19,28,11,8,13,9,4
84069,5,3,0,0,0,4,1,5,0,4,...,0,0,0,0,2,4,2,0,0,0

In [44]:
df_nodup2.to_csv('GSE126848_nodup.entrezid.txt',sep='\t')

---
### unigene

In [46]:
import pandas_explode 
pandas_explode.patch()

df_result = df_nodup2
mg = mygene.MyGeneInfo()
mg_dict2 = mg.querymany(df_result.index,scopes='refseq,symbol,entrezgene,reporter,unigene', field=['entrezgene','unigene'], species='human')
mg_df2 = pd.DataFrame.from_dict(mg_dict2)

querying 1-1000...done.
querying 1001-2000...done.
querying 2001-3000...done.
querying 3001-4000...done.
querying 4001-5000...done.
querying 5001-6000...done.
querying 6001-7000...done.
querying 7001-8000...done.
querying 8001-9000...done.
querying 9001-10000...done.
querying 10001-11000...done.
querying 11001-12000...done.
querying 12001-13000...done.
querying 13001-14000...done.
querying 14001-15000...done.
querying 15001-16000...done.
querying 16001-17000...done.
querying 17001-18000...done.
querying 18001-19000...done.
querying 19001-19175...done.
Finished.

In [47]:
mg_df2 = pd.DataFrame.from_dict(mg_dict2)
mg_df2 = mg_df2[['query','unigene','entrezgene']]
mg_df2 = mg_df2[~mg_df2.unigene.isna()]
mg_df2.unigene = [ [m] if type(m)==str else m for m in mg_df2.unigene ]
mg_df2.head()

    query      unigene entrezgene
0   79501  [Hs.554500]      79501
1  148398  [Hs.335293]     148398
2   26155  [Hs.405987]      26155
3  339451  [Hs.109212]     339451
4   84069  [Hs.528691]      84069

In [48]:
mg_df2.explode('unigene')[['entrezgene','unigene']].to_csv('GSE126848.unigene.csv', index=False)