# GEOparse
https://geoparse.readthedocs.io/en/latest/GEOparse.html

In [1]:
import GEOparse
import pandas as pd
import mygene

In [2]:
import pylab as pl
import seaborn as sns
pl.rcParams['figure.figsize'] = (14, 10)
pl.rcParams['ytick.labelsize'] = 12
pl.rcParams['xtick.labelsize'] = 11
pl.rcParams['axes.labelsize'] = 23
pl.rcParams['legend.fontsize'] = 20
sns.set_style('ticks')
c1, c2, c3, c4 = sns.color_palette("Set1", 4)

In [3]:
gse = GEOparse.get_GEO("GSE83452")

08-Sep-2020 11:31:22 DEBUG utils - Directory ./ already exists. Skipping.
08-Sep-2020 11:31:22 INFO GEOparse - File already exist: using local version.
08-Sep-2020 11:31:22 INFO GEOparse - Parsing ./GSE83452_family.soft.gz:
08-Sep-2020 11:31:22 DEBUG GEOparse - DATABASE: GeoMiame
08-Sep-2020 11:31:22 DEBUG GEOparse - SERIES: GSE83452
08-Sep-2020 11:31:22 DEBUG GEOparse - PLATFORM: GPL16686
08-Sep-2020 11:31:22 DEBUG GEOparse - SAMPLE: GSM2203254
08-Sep-2020 11:31:23 DEBUG GEOparse - SAMPLE: GSM2203255
08-Sep-2020 11:31:23 DEBUG GEOparse - SAMPLE: GSM2203256
08-Sep-2020 11:31:23 DEBUG GEOparse - SAMPLE: GSM2203257
08-Sep-2020 11:31:23 DEBUG GEOparse - SAMPLE: GSM2203258
08-Sep-2020 11:31:23 DEBUG GEOparse - SAMPLE: GSM2203259
08-Sep-2020 11:31:23 DEBUG GEOparse - SAMPLE: GSM2203260
08-Sep-2020 11:31:23 DEBUG GEOparse - SAMPLE: GSM2203261
08-Sep-2020 11:31:23 DEBUG GEOparse - SAMPLE: GSM2203262
08-Sep-2020 11:31:24 DEBUG GEOparse - SAMPLE: GSM2203263
08-Sep-2020 11:31:24 DEBUG GEOparse - SAMPLE: GSM2203264
08-Sep-2020 11:31:24 DEBUG GEOparse - SAMPLE: GSM2203265
08-Sep-2020 11:31:24 DEBUG GEOparse - SAMPLE: GSM2203266
08-Sep-2020 11:31:24 DEBUG GEOparse - SAMPLE: GSM2203267
08-Sep-2020 11:31:24 DEBUG GEOparse - SAMPLE: GSM2203268
08-Sep-2020 11:31:24 DEBUG GEOparse - SAMPLE: GSM2203269
08-Sep-2020 11:31:24 DEBUG GEOparse - SAMPLE: GSM2203270
08-Sep-2020 11:31:24 DEBUG GEOparse - SAMPLE: GSM2203271
08-Sep-2020 11:31:25 DEBUG GEOparse - SAMPLE: GSM2203272
08-Sep-2020 11:31:25 DEBUG GEOparse - SAMPLE: GSM2203273
08-Sep-2020 11:31:25 DEBUG GEOparse - SAMPLE: GSM2203274
08-Sep-2020 11:31:25 DEBUG GEOparse - SAMPLE: GSM2203275
08-Sep-2020 11:31:25 DEBUG GEOparse - SAMPLE: GSM2203276
08-Sep-2020 11:31:25 DEBUG GEOparse - SAMPLE: GSM2203277
08-Sep-2020 11:31:25 DEBUG GEOparse - SAMPLE: GSM2203278
08-Sep-2020 11:31:25 DEBUG GEOparse - SAMPLE: GSM2203279
08-Sep-2020 11:31:26 DEBUG GEOparse - SAMPLE: GSM2203280
08-Sep-2020 11:31:26 DEBUG GEOparse - SAMPLE: GSM2203281
08-Sep-2020 11:31:26 DEBUG GEOparse - SAMPLE: GSM2203282
08-Sep-2020 11:31:26 DEBUG GEOparse - SAMPLE: GSM2203283
08-Sep-2020 11:31:26 DEBUG GEOparse - SAMPLE: GSM2203284
08-Sep-2020 11:31:26 DEBUG GEOparse - SAMPLE: GSM2203285
08-Sep-2020 11:31:26 DEBUG GEOparse - SAMPLE: GSM2203286
08-Sep-2020 11:31:27 DEBUG GEOparse - SAMPLE: GSM2203287
08-Sep-2020 11:31:27 DEBUG GEOparse - SAMPLE: GSM2203288
08-Sep-2020 11:31:27 DEBUG GEOparse - SAMPLE: GSM2203289
08-Sep-2020 11:31:27 DEBUG GEOparse - SAMPLE: GSM2203290
08-Sep-2020 11:31:27 DEBUG GEOparse - SAMPLE: GSM2203291
08-Sep-2020 11:31:27 DEBUG GEOparse - SAMPLE: GSM2203292
08-Sep-2020 11:31:27 DEBUG GEOparse - SAMPLE: GSM2203293
08-Sep-2020 11:31:27 DEBUG GEOparse - SAMPLE: GSM2203294
08-Sep-2020 11:31:28 DEBUG GEOparse - SAMPLE: GSM2203295
08-Sep-2020 11:31:28 DEBUG GEOparse - SAMPLE: GSM2203296
08-Sep-2020 11:31:28 DEBUG GEOparse - SAMPLE: GSM2203297
08-Sep-2020 11:31:28 DEBUG GEOparse - SAMPLE: GSM2203298
08-Sep-2020 11:31:28 DEBUG GEOparse - SAMPLE: GSM2203299
08-Sep-2020 11:31:28 DEBUG GEOparse - SAMPLE: GSM2203300
08-Sep-2020 11:31:28 DEBUG GEOparse - SAMPLE: GSM2203301
08-Sep-2020 11:31:28 DEBUG GEOparse - SAMPLE: GSM2203302
08-Sep-2020 11:31:28 DEBUG GEOparse - SAMPLE: GSM2203303
08-Sep-2020 11:31:29 DEBUG GEOparse - SAMPLE: GSM2203304
08-Sep-2020 11:31:29 DEBUG GEOparse - SAMPLE: GSM2203305
08-Sep-2020 11:31:29 DEBUG GEOparse - SAMPLE: GSM2203306
08-Sep-2020 11:31:29 DEBUG GEOparse - SAMPLE: GSM2203307
08-Sep-2020 11:31:29 DEBUG GEOparse - SAMPLE: GSM2203308
08-Sep-2020 11:31:29 DEBUG GEOparse - SAMPLE: GSM2203309
08-Sep-2020 11:31:29 DEBUG GEOparse - SAMPLE: GSM2203310
08-Sep-2020 11:31:29 DEBUG GEOparse - SAMPLE: GSM2203311
08-Sep-2020 11:31:30 DEBUG GEOparse - SAMPLE: GSM2203312
08-Sep-2020 11:31:30 DEBUG GEOparse - SAMPLE: GSM2203313
08-Sep-2020 11:31:30 DEBUG GEOparse - SAMPLE: GSM2203314
08-Sep-2020 11:31:30 DEBUG GEOparse - SAMPLE: GSM2203315
08-Sep-2020 11:31:30 DEBUG GEOparse - SAMPLE: GSM2203316
08-Sep-2020 11:31:30 DEBUG GEOparse - SAMPLE: GSM2203317
08-Sep-2020 11:31:30 DEBUG GEOparse - SAMPLE: GSM2203318
08-Sep-2020 11:31:30 DEBUG GEOparse - SAMPLE: GSM2203319
08-Sep-2020 11:31:31 DEBUG GEOparse - SAMPLE: GSM2203320
08-Sep-2020 11:31:31 DEBUG GEOparse - SAMPLE: GSM2203321
08-Sep-2020 11:31:31 DEBUG GEOparse - SAMPLE: GSM2203322
08-Sep-2020 11:31:31 DEBUG GEOparse - SAMPLE: GSM2203323
08-Sep-2020 11:31:31 DEBUG GEOparse - SAMPLE: GSM2203324
08-Sep-2020 11:31:31 DEBUG GEOparse - SAMPLE: GSM2203325
08-Sep-2020 11:31:31 DEBUG GEOparse - SAMPLE: GSM2203326
08-Sep-2020 11:31:31 DEBUG GEOparse - SAMPLE: GSM2203327
08-Sep-2020 11:31:31 DEBUG GEOparse - SAMPLE: GSM2203328
08-Sep-2020 11:31:32 DEBUG GEOparse - SAMPLE: GSM2203329
08-Sep-2020 11:31:32 DEBUG GEOparse - SAMPLE: GSM2203330
08-Sep-2020 11:31:32 DEBUG GEOparse - SAMPLE: GSM2203331
08-Sep-2020 11:31:32 DEBUG GEOparse - SAMPLE: GSM2203332
08-Sep-2020 11:31:32 DEBUG GEOparse - SAMPLE: GSM2203333
08-Sep-2020 11:31:32 DEBUG GEOparse - SAMPLE: GSM2203334
08-Sep-2020 11:31:32 DEBUG GEOparse - SAMPLE: GSM2203335
08-Sep-2020 11:31:32 DEBUG GEOparse - SAMPLE: GSM2203336
08-Sep-2020 11:31:33 DEBUG GEOparse - SAMPLE: GSM2203337
08-Sep-2020 11:31:33 DEBUG GEOparse - SAMPLE: GSM2203338
08-Sep-2020 11:31:33 DEBUG GEOparse - SAMPLE: GSM2203339
08-Sep-2020 11:31:33 DEBUG GEOparse - SAMPLE: GSM2203340
08-Sep-2020 11:31:33 DEBUG GEOparse - SAMPLE: GSM2203341
08-Sep-2020 11:31:33 DEBUG GEOparse - SAMPLE: GSM2203342
08-Sep-2020 11:31:33 DEBUG GEOparse - SAMPLE: GSM2203343
08-Sep-2020 11:31:33 DEBUG GEOparse - SAMPLE: GSM2203344
08-Sep-2020 11:31:34 DEBUG GEOparse - SAMPLE: GSM2203345
08-Sep-2020 11:31:34 DEBUG GEOparse - SAMPLE: GSM2203346
08-Sep-2020 11:31:34 DEBUG GEOparse - SAMPLE: GSM2203347
08-Sep-2020 11:31:34 DEBUG GEOparse - SAMPLE: GSM2203348
08-Sep-2020 11:31:34 DEBUG GEOparse - SAMPLE: GSM2203349
08-Sep-2020 11:31:34 DEBUG GEOparse - SAMPLE: GSM2203350
08-Sep-2020 11:31:34 DEBUG GEOparse - SAMPLE: GSM2203351
08-Sep-2020 11:31:34 DEBUG GEOparse - SAMPLE: GSM2203352
08-Sep-2020 11:31:34 DEBUG GEOparse - SAMPLE: GSM2203353
08-Sep-2020 11:31:35 DEBUG GEOparse - SAMPLE: GSM2203354
08-Sep-2020 11:31:35 DEBUG GEOparse - SAMPLE: GSM2203355
08-Sep-2020 11:31:35 DEBUG GEOparse - SAMPLE: GSM2203356
08-Sep-2020 11:31:35 DEBUG GEOparse - SAMPLE: GSM2203357
08-Sep-2020 11:31:35 DEBUG GEOparse - SAMPLE: GSM2203358
08-Sep-2020 11:31:35 DEBUG GEOparse - SAMPLE: GSM2203359
08-Sep-2020 11:31:35 DEBUG GEOparse - SAMPLE: GSM2203360
08-Sep-2020 11:31:35 DEBUG GEOparse - SAMPLE: GSM2203361
08-Sep-2020 11:31:36 DEBUG GEOparse - SAMPLE: GSM2203362
08-Sep-2020 11:31:36 DEBUG GEOparse - SAMPLE: GSM2203363
08-Sep-2020 11:31:36 DEBUG GEOparse - SAMPLE: GSM2203364
08-Sep-2020 11:31:36 DEBUG GEOparse - SAMPLE: GSM2203365
08-Sep-2020 11:31:36 DEBUG GEOparse - SAMPLE: GSM2203366
08-Sep-2020 11:31:36 DEBUG GEOparse - SAMPLE: GSM2203367
08-Sep-2020 11:31:36 DEBUG GEOparse - SAMPLE: GSM2203368
08-Sep-2020 11:31:36 DEBUG GEOparse - SAMPLE: GSM2203369
08-Sep-2020 11:31:37 DEBUG GEOparse - SAMPLE: GSM2203370
08-Sep-2020 11:31:37 DEBUG GEOparse - SAMPLE: GSM2203371
08-Sep-2020 11:31:37 DEBUG GEOparse - SAMPLE: GSM2203372
08-Sep-2020 11:31:37 DEBUG GEOparse - SAMPLE: GSM2203373
08-Sep-2020 11:31:37 DEBUG GEOparse - SAMPLE: GSM2203374
08-Sep-2020 11:31:37 DEBUG GEOparse - SAMPLE: GSM2203375
08-Sep-2020 11:31:37 DEBUG GEOparse - SAMPLE: GSM2203376
08-Sep-2020 11:31:37 DEBUG GEOparse - SAMPLE: GSM2203377
08-Sep-2020 11:31:37 DEBUG GEOparse - SAMPLE: GSM2203378
08-Sep-2020 11:31:38 DEBUG GEOparse - SAMPLE: GSM2203379
08-Sep-2020 11:31:38 DEBUG GEOparse - SAMPLE: GSM2203380
08-Sep-2020 11:31:38 DEBUG GEOparse - SAMPLE: GSM2203381
08-Sep-2020 11:31:38 DEBUG GEOparse - SAMPLE: GSM2203382
08-Sep-2020 11:31:38 DEBUG GEOparse - SAMPLE: GSM2203383
08-Sep-2020 11:31:38 DEBUG GEOparse - SAMPLE: GSM2203384
08-Sep-2020 11:31:38 DEBUG GEOparse - SAMPLE: GSM2203385
08-Sep-2020 11:31:38 DEBUG GEOparse - SAMPLE: GSM2203386
08-Sep-2020 11:31:39 DEBUG GEOparse - SAMPLE: GSM2203387
08-Sep-2020 11:31:39 DEBUG GEOparse - SAMPLE: GSM2203388
08-Sep-2020 11:31:39 DEBUG GEOparse - SAMPLE: GSM2203389
08-Sep-2020 11:31:39 DEBUG GEOparse - SAMPLE: GSM2203390
08-Sep-2020 11:31:39 DEBUG GEOparse - SAMPLE: GSM2203391
08-Sep-2020 11:31:39 DEBUG GEOparse - SAMPLE: GSM2203392
08-Sep-2020 11:31:39 DEBUG GEOparse - SAMPLE: GSM2203393
08-Sep-2020 11:31:39 DEBUG GEOparse - SAMPLE: GSM2203394
08-Sep-2020 11:31:40 DEBUG GEOparse - SAMPLE: GSM2203395
08-Sep-2020 11:31:40 DEBUG GEOparse - SAMPLE: GSM2203396
08-Sep-2020 11:31:40 DEBUG GEOparse - SAMPLE: GSM2203397
08-Sep-2020 11:31:40 DEBUG GEOparse - SAMPLE: GSM2203398
08-Sep-2020 11:31:40 DEBUG GEOparse - SAMPLE: GSM2203399
08-Sep-2020 11:31:40 DEBUG GEOparse - SAMPLE: GSM2203400
08-Sep-2020 11:31:40 DEBUG GEOparse - SAMPLE: GSM2203401
08-Sep-2020 11:31:40 DEBUG GEOparse - SAMPLE: GSM2203402
08-Sep-2020 11:31:40 DEBUG GEOparse - SAMPLE: GSM2203403
08-Sep-2020 11:31:41 DEBUG GEOparse - SAMPLE: GSM2203404
08-Sep-2020 11:31:41 DEBUG GEOparse - SAMPLE: GSM2203405
08-Sep-2020 11:31:41 DEBUG GEOparse - SAMPLE: GSM2203406
08-Sep-2020 11:31:41 DEBUG GEOparse - SAMPLE: GSM2203407
08-Sep-2020 11:31:41 DEBUG GEOparse - SAMPLE: GSM2203408
08-Sep-2020 11:31:41 DEBUG GEOparse - SAMPLE: GSM2203409
08-Sep-2020 11:31:41 DEBUG GEOparse - SAMPLE: GSM2203410
08-Sep-2020 11:31:41 DEBUG GEOparse - SAMPLE: GSM2203411
08-Sep-2020 11:31:42 DEBUG GEOparse - SAMPLE: GSM2203412
08-Sep-2020 11:31:42 DEBUG GEOparse - SAMPLE: GSM2203413
08-Sep-2020 11:31:42 DEBUG GEOparse - SAMPLE: GSM2203414
08-Sep-2020 11:31:42 DEBUG GEOparse - SAMPLE: GSM2203415
08-Sep-2020 11:31:42 DEBUG GEOparse - SAMPLE: GSM2203416
08-Sep-2020 11:31:42 DEBUG GEOparse - SAMPLE: GSM2203417
08-Sep-2020 11:31:42 DEBUG GEOparse - SAMPLE: GSM2203418
08-Sep-2020 11:31:42 DEBUG GEOparse - SAMPLE: GSM2203419
08-Sep-2020 11:31:43 DEBUG GEOparse - SAMPLE: GSM2203420
08-Sep-2020 11:31:43 DEBUG GEOparse - SAMPLE: GSM2203421
08-Sep-2020 11:31:43 DEBUG GEOparse - SAMPLE: GSM2203422
08-Sep-2020 11:31:43 DEBUG GEOparse - SAMPLE: GSM2203423
08-Sep-2020 11:31:43 DEBUG GEOparse - SAMPLE: GSM2203424
08-Sep-2020 11:31:43 DEBUG GEOparse - SAMPLE: GSM2203425
08-Sep-2020 11:31:43 DEBUG GEOparse - SAMPLE: GSM2203426
08-Sep-2020 11:31:43 DEBUG GEOparse - SAMPLE: GSM2203427
08-Sep-2020 11:31:43 DEBUG GEOparse - SAMPLE: GSM2203428
08-Sep-2020 11:31:44 DEBUG GEOparse - SAMPLE: GSM2203429
08-Sep-2020 11:31:44 DEBUG GEOparse - SAMPLE: GSM2203430
08-Sep-2020 11:31:44 DEBUG GEOparse - SAMPLE: GSM2203431
08-Sep-2020 11:31:44 DEBUG GEOparse - SAMPLE: GSM2203432
08-Sep-2020 11:31:44 DEBUG GEOparse - SAMPLE: GSM2203433
08-Sep-2020 11:31:44 DEBUG GEOparse - SAMPLE: GSM2203434
08-Sep-2020 11:31:44 DEBUG GEOparse - SAMPLE: GSM2203435
08-Sep-2020 11:31:44 DEBUG GEOparse - SAMPLE: GSM2203436
08-Sep-2020 11:31:45 DEBUG GEOparse - SAMPLE: GSM2203437
08-Sep-2020 11:31:45 DEBUG GEOparse - SAMPLE: GSM2203438
08-Sep-2020 11:31:45 DEBUG GEOparse - SAMPLE: GSM2203439
08-Sep-2020 11:31:45 DEBUG GEOparse - SAMPLE: GSM2203440
08-Sep-2020 11:31:45 DEBUG GEOparse - SAMPLE: GSM2203441
08-Sep-2020 11:31:45 DEBUG GEOparse - SAMPLE: GSM2203442
08-Sep-2020 11:31:45 DEBUG GEOparse - SAMPLE: GSM2203443
08-Sep-2020 11:31:45 DEBUG GEOparse - SAMPLE: GSM2203444
08-Sep-2020 11:31:46 DEBUG GEOparse - SAMPLE: GSM2203445
08-Sep-2020 11:31:46 DEBUG GEOparse - SAMPLE: GSM2203446
08-Sep-2020 11:31:46 DEBUG GEOparse - SAMPLE: GSM2203447
08-Sep-2020 11:31:46 DEBUG GEOparse - SAMPLE: GSM2203448
08-Sep-2020 11:31:46 DEBUG GEOparse - SAMPLE: GSM2203449
08-Sep-2020 11:31:46 DEBUG GEOparse - SAMPLE: GSM2203450
08-Sep-2020 11:31:46 DEBUG GEOparse - SAMPLE: GSM2203451
08-Sep-2020 11:31:46 DEBUG GEOparse - SAMPLE: GSM2203452
08-Sep-2020 11:31:47 DEBUG GEOparse - SAMPLE: GSM2203453
08-Sep-2020 11:31:47 DEBUG GEOparse - SAMPLE: GSM2203454
08-Sep-2020 11:31:47 DEBUG GEOparse - SAMPLE: GSM2203455
08-Sep-2020 11:31:47 DEBUG GEOparse - SAMPLE: GSM2203456
08-Sep-2020 11:31:47 DEBUG GEOparse - SAMPLE: GSM2203457
08-Sep-2020 11:31:47 DEBUG GEOparse - SAMPLE: GSM2203458
08-Sep-2020 11:31:47 DEBUG GEOparse - SAMPLE: GSM2203459
08-Sep-2020 11:31:47 DEBUG GEOparse - SAMPLE: GSM2203460
08-Sep-2020 11:31:47 DEBUG GEOparse - SAMPLE: GSM2203461
08-Sep-2020 11:31:48 DEBUG GEOparse - SAMPLE: GSM2203462
08-Sep-2020 11:31:48 DEBUG GEOparse - SAMPLE: GSM2203463
08-Sep-2020 11:31:48 DEBUG GEOparse - SAMPLE: GSM2203464
08-Sep-2020 11:31:48 DEBUG GEOparse - SAMPLE: GSM2203465
08-Sep-2020 11:31:48 DEBUG GEOparse - SAMPLE: GSM2203466
08-Sep-2020 11:31:48 DEBUG GEOparse - SAMPLE: GSM2203467
08-Sep-2020 11:31:48 DEBUG GEOparse - SAMPLE: GSM2203468
08-Sep-2020 11:31:48 DEBUG GEOparse - SAMPLE: GSM2203469
08-Sep-2020 11:31:49 DEBUG GEOparse - SAMPLE: GSM2203470
08-Sep-2020 11:31:49 DEBUG GEOparse - SAMPLE: GSM2203471
08-Sep-2020 11:31:49 DEBUG GEOparse - SAMPLE: GSM2203472
08-Sep-2020 11:31:49 DEBUG GEOparse - SAMPLE: GSM2203473
08-Sep-2020 11:31:49 DEBUG GEOparse - SAMPLE: GSM2203474
08-Sep-2020 11:31:49 DEBUG GEOparse - SAMPLE: GSM2203475
08-Sep-2020 11:31:49 DEBUG GEOparse - SAMPLE: GSM2203476
08-Sep-2020 11:31:49 DEBUG GEOparse - SAMPLE: GSM2203477
08-Sep-2020 11:31:50 DEBUG GEOparse - SAMPLE: GSM2203478
08-Sep-2020 11:31:50 DEBUG GEOparse - SAMPLE: GSM2203479
08-Sep-2020 11:31:50 DEBUG GEOparse - SAMPLE: GSM2203480
08-Sep-2020 11:31:50 DEBUG GEOparse - SAMPLE: GSM2203481
08-Sep-2020 11:31:50 DEBUG GEOparse - SAMPLE: GSM2203482
08-Sep-2020 11:31:50 DEBUG GEOparse - SAMPLE: GSM2203483
08-Sep-2020 11:31:50 DEBUG GEOparse - SAMPLE: GSM2203484

In [58]:
gse.gpls

{'GPL16686': <d: GPL16686>}

In [5]:
gse.gpls['GPL16686'].columns

                                                    description
ID            transcript_cluster_id LINK_PRE:"https://www.af...
RANGE_STRAND                                      strand  (+|-)
RANGE_START   start  (integer). Coordinates are standard 1-b...
RANGE_END
total_probes  Total number of probes contained by this trans...
GB_ACC        GenBank and RefSeq Accessions from mrna_assign...
SPOT_ID       genomic location of the transcript cluster in ...
RANGE_GB            NCBI RefSeq for chromosome of current build

In [6]:
gse.gsms["GSM2203483"].columns

            description
ID_REF
VALUE   Log2 RMA signal

In [7]:
%%time

df = gse.pivot_samples('VALUE')

CPU times: user 24.6 s, sys: 2.74 s, total: 27.3 s
Wall time: 11.2 s

In [8]:
df.index = df.index.map(str)

In [9]:
df.index

Index(['16650001', '16650003', '16650005', '16650007', '16650009', '16650011',
       '16650013', '16650015', '16650017', '16650019',
       ...
       '17127703', '17127705', '17127707', '17127709', '17127711', '17127713',
       '17127715', '17127717', '17127719', '17127721'],
      dtype='object', name='ID_REF', length=53617)

In [10]:
info = gse.gpls['GPL16686'].table
info = info.set_index('ID')
info.head()

,RANGE_STRAND,RANGE_START,RANGE_END,total_probes,GB_ACC,SPOT_ID,RANGE_GB
ID,,,,,,,
16657436,+,12190.0,13639.0,25.0,NR_046018,chr1:12190-13639,NC_000001.10
16657440,+,29554.0,31109.0,28.0,NaN,chr1:29554-31109,NC_000001.10
16657445,+,69091.0,70008.0,8.0,NaN,chr1:69091-70008,NC_000001.10
16657447,+,160446.0,161525.0,13.0,NaN,chr1:160446-161525,NC_000001.10
16657450,+,317811.0,328581.0,36.0,NR_024368,chr1:317811-328581,NC_000001.10

In [11]:
info_dict = info['GB_ACC'].to_dict()

In [12]:
df.index = df.index.map(info_dict)

In [14]:
df = df[~pd.isnull(df.index)]
df.head()

name,GSM2203254,GSM2203255,GSM2203256,GSM2203257,GSM2203258,GSM2203259,GSM2203260,GSM2203261,GSM2203262,GSM2203263,...,GSM2203475,GSM2203476,GSM2203477,GSM2203478,GSM2203479,GSM2203480,GSM2203481,GSM2203482,GSM2203483,GSM2203484
ID_REF,,,,,,,,,,,,,,,,,,,,,
NR_046018,4.65239,4.90529,4.30379,4.89175,4.56044,4.12404,4.29589,4.88249,4.48308,4.94610,...,4.79016,4.74030,5.06400,4.43811,5.05924,5.38884,4.74714,4.55271,4.45428,5.35202
NR_024368,7.85355,8.34474,8.09215,8.19768,8.60365,7.47333,8.42662,8.16026,8.60682,8.80425,...,8.43926,8.40739,8.48326,8.32463,8.63938,8.29297,8.99647,8.70076,8.47286,8.70961
NR_029406,4.73643,4.89157,4.96938,4.43918,4.82888,4.26771,4.55758,5.27251,5.38908,5.60109,...,4.69459,4.77866,4.58755,4.57725,4.91118,4.53805,4.56812,4.66221,4.57837,4.62134
XR_132471,3.37093,3.79917,3.33363,3.31480,2.90822,3.29387,3.26061,2.93083,3.10190,3.23685,...,3.45015,3.94509,4.05813,3.52192,3.50057,4.12271,3.37705,3.67065,3.70919,3.38360
NR_047526,4.94681,5.35731,5.19168,4.79888,5.25922,5.30605,4.86141,5.22193,4.94268,5.57056,...,5.03432,5.18109,5.52809,4.57324,6.07874,5.40930,6.29415,4.98093,5.61195,5.10416

In [34]:
df.shape

(17623, 231)

---
### mygene mapping

In [25]:
%%time
mg = mygene.MyGeneInfo()
mg_dict = mg.querymany(df.index,scopes='refseq,symbol,entrezgene,reporter,uniprot', species='human')

querying 1-1000...done.
querying 1001-2000...done.
querying 2001-3000...done.
querying 3001-4000...done.
querying 4001-5000...done.
querying 5001-6000...done.
querying 6001-7000...done.
querying 7001-8000...done.
querying 8001-9000...done.
querying 9001-10000...done.
querying 10001-11000...done.
querying 11001-12000...done.
querying 12001-13000...done.
querying 13001-14000...done.
querying 14001-15000...done.
querying 15001-16000...done.
querying 16001-17000...done.
querying 17001-17623...done.
Finished.
744 input query terms found dup hits:
	[('NR_024368', 3), ('NR_029406', 4), ('NR_026927', 2), ('NR_024455', 2), ('NM_015074', 2), ('NM_0010
679 input query terms found no hit:
	['XR_132471', 'NM_001045480', 'XM_001715369', 'NR_033264', 'NR_037643', 'NR_037185', 'XR_110493', 'X
Pass "returnall=True" to return complete lists of duplicate or missing query terms.
CPU times: user 349 ms, sys: 28.6 ms, total: 378 ms
Wall time: 1min 29s

In [37]:
dup_df = df.loc[df[df.index.duplicated()].index]  ## 어떤 row를 살릴지 데이터 살펴보고 결정.
len(dup_df.index.unique()), dup_df.shape

(798, (5198, 231))

In [41]:
df_nodup = df.groupby(df.index).mean()

In [42]:
df_nodup.head()

name,GSM2203254,GSM2203255,GSM2203256,GSM2203257,GSM2203258,GSM2203259,GSM2203260,GSM2203261,GSM2203262,GSM2203263,...,GSM2203475,GSM2203476,GSM2203477,GSM2203478,GSM2203479,GSM2203480,GSM2203481,GSM2203482,GSM2203483,GSM2203484
ID_REF,,,,,,,,,,,,,,,,,,,,,
NM_000014,10.43240,10.49460,10.14020,10.37430,10.94120,9.55988,10.82850,10.13010,10.72650,9.86607,...,10.06980,9.65479,10.93620,10.26330,10.04010,11.22930,10.79370,10.46890,9.44561,10.83820
NM_000015,6.54655,6.28379,6.48029,6.48616,6.67406,6.39948,6.90617,6.30154,6.65563,6.51159,...,6.12036,6.29840,6.74164,6.45598,6.61122,6.20426,6.18340,6.17424,6.93548,6.58564
NM_000019,6.15803,6.52002,5.65829,5.96784,6.16960,6.28782,5.84854,6.14519,6.05021,5.76786,...,6.24971,6.17343,6.24240,6.07688,6.51640,5.95967,6.20088,6.28232,6.28731,6.02145
NM_000020,4.96623,4.55525,5.30811,4.96695,4.75641,4.89262,5.16423,4.45618,4.68070,5.04424,...,5.05271,5.10562,5.01800,4.99643,5.06582,5.31840,5.01894,5.19946,5.00202,5.47749
NM_000021,5.48845,5.57815,5.46861,5.89164,5.51627,5.37065,5.36439,5.10761,5.45658,5.38372,...,5.16952,5.11457,5.36883,5.62253,5.51119,5.56221,5.64991,5.14726,5.87694,5.77886

In [43]:
mg_nodup_dict = mg.querymany(df_nodup.index,scopes='refseq,symbol,entrezgene,reporter,uniprot', species='human')

querying 1-1000...done.
querying 1001-2000...done.
querying 2001-3000...done.
querying 3001-4000...done.
querying 4001-5000...done.
querying 5001-6000...done.
querying 6001-7000...done.
querying 7001-8000...done.
querying 8001-9000...done.
querying 9001-10000...done.
querying 10001-11000...done.
querying 11001-12000...done.
querying 12001-13000...done.
querying 13001-14000...done.
querying 14001-15000...done.
querying 15001-16000...done.
querying 16001-16346...done.
Finished.
585 input query terms found no hit:
	['NM_000060', 'NM_001001709', 'NM_001001891', 'NM_001008737', 'NM_001012715', 'NM_001013692', 'NM_00
Pass "returnall=True" to return complete lists of duplicate or missing query terms.

In [46]:
mg_nodup = [ q_dict for q_dict in mg_nodup_dict if 'notfound' not in q_dict.keys()]

In [50]:
mg_nodup_df = pd.DataFrame.from_dict(mg_nodup).set_index('query')
mg_nodup_df.head()

,_id,_score,entrezgene,name,symbol,taxid
query,,,,,,
NM_000014,2,17.574873,2,alpha-2-macroglobulin,A2M,9606
NM_000015,10,25.817316,10,N-acetyltransferase 2,NAT2,9606
NM_000019,38,5.570232,38,acetyl-CoA acetyltransferase 1,ACAT1,9606
NM_000020,94,17.560099,94,activin A receptor like type 1,ACVRL1,9606
NM_000021,5663,13.667017,5663,presenilin 1,PSEN1,9606

In [59]:
indice = mg_nodup_df.groupby('entrezgene')['_score'].idxmax()
mg_nodup_df.loc[indice].head()

,_id,_score,entrezgene,name,symbol,taxid
query,,,,,,
NM_130786,1,32.291050,1,alpha-1-B glycoprotein,A1BG,9606
NM_000015,10,25.817316,10,N-acetyltransferase 2,NAT2,9606
NM_000022,100,21.183740,100,adenosine deaminase,ADA,9606
NR_024407,100009676,36.073627,100009676,ZBTB11 antisense RNA 1,ZBTB11-AS1,9606
NM_005466,10001,19.835154,10001,mediator complex subunit 6,MED6,9606

In [60]:
dict_df = mg_nodup_df.loc[indice]
dict_entrezgene = dict_df.entrezgene.to_dict()

In [64]:
indice_n = df_nodup.index[~df_nodup.index.map(dict_entrezgene).isna()]
new_index = df_nodup.loc[indice_n].index.map(dict_entrezgene)
df_result = df_nodup.loc[indice_n]
df_result.index=new_index
df_result = df_result.fillna(0)
df_result.to_csv('GSE83452_nodup.entrezid.txt',sep='\t')

---
### unigene

In [65]:
import pandas_explode 
pandas_explode.patch()

mg = mygene.MyGeneInfo()
mg_dict2 = mg.querymany(df_result.index,scopes='refseq,symbol,entrezgene,reporter,unigene', field=['entrezgene','unigene'], species='human')
mg_df2 = pd.DataFrame.from_dict(mg_dict2)

querying 1-1000...done.
querying 1001-2000...done.
querying 2001-3000...done.
querying 3001-4000...done.
querying 4001-5000...done.
querying 5001-6000...done.
querying 6001-7000...done.
querying 7001-8000...done.
querying 8001-9000...done.
querying 9001-10000...done.
querying 10001-11000...done.
querying 11001-12000...done.
querying 12001-13000...done.
querying 13001-14000...done.
querying 14001-15000...done.
querying 15001-15643...done.
Finished.

In [66]:
mg_df2 = pd.DataFrame.from_dict(mg_dict2)
mg_df2 = mg_df2[['query','unigene','entrezgene']]
mg_df2 = mg_df2[~mg_df2.unigene.isna()]
mg_df2.unigene = [ [m] if type(m)==str else m for m in mg_df2.unigene ]
mg_df2.head()

  query                unigene entrezgene
0     2  [Hs.212838, Hs.88556]          2
1    10                 [Hs.2]         10
2    38            [Hs.232375]         38
3    94            [Hs.591026]         94
4  5663              [Hs.3260]       5663

In [68]:
mg_df2.explode('unigene')[['entrezgene','unigene']].to_csv('GSE83452.unigene.csv', index=False)

---
옛날코드

In [52]:
df_nodup.shape, mg_nodup_df.shape

((16346, 231), (15761, 6))

In [54]:
df_result = df_nodup[df_nodup.index.isin(mg_nodup_df.index)]
df_result.insert(0,'entrezgene',mg_nodup_df.entrezgene)

In [56]:
df_result = df_result.set_index('entrezgene', drop=True)
df_result.head()

name,GSM2203254,GSM2203255,GSM2203256,GSM2203257,GSM2203258,GSM2203259,GSM2203260,GSM2203261,GSM2203262,GSM2203263,...,GSM2203475,GSM2203476,GSM2203477,GSM2203478,GSM2203479,GSM2203480,GSM2203481,GSM2203482,GSM2203483,GSM2203484
entrezgene,,,,,,,,,,,,,,,,,,,,,
2,10.43240,10.49460,10.14020,10.37430,10.94120,9.55988,10.82850,10.13010,10.72650,9.86607,...,10.06980,9.65479,10.93620,10.26330,10.04010,11.22930,10.79370,10.46890,9.44561,10.83820
10,6.54655,6.28379,6.48029,6.48616,6.67406,6.39948,6.90617,6.30154,6.65563,6.51159,...,6.12036,6.29840,6.74164,6.45598,6.61122,6.20426,6.18340,6.17424,6.93548,6.58564
38,6.15803,6.52002,5.65829,5.96784,6.16960,6.28782,5.84854,6.14519,6.05021,5.76786,...,6.24971,6.17343,6.24240,6.07688,6.51640,5.95967,6.20088,6.28232,6.28731,6.02145
94,4.96623,4.55525,5.30811,4.96695,4.75641,4.89262,5.16423,4.45618,4.68070,5.04424,...,5.05271,5.10562,5.01800,4.99643,5.06582,5.31840,5.01894,5.19946,5.00202,5.47749
5663,5.48845,5.57815,5.46861,5.89164,5.51627,5.37065,5.36439,5.10761,5.45658,5.38372,...,5.16952,5.11457,5.36883,5.62253,5.51119,5.56221,5.64991,5.14726,5.87694,5.77886

In [57]:
df_result.to_csv('GSE83452_nodup.entrezid.txt',sep='\t')